FROM node:14.17.5-alpine AS builder

WORKDIR /app

COPY package.json .

RUN yarn install

COPY . .

RUN yarn build

FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/build usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]
